mask_path: /home/worker/mask-rcnn-web/models/frame_mask
model_weights_path: /home/worker/mask-rcnn-web/instance/weights/mrcnn.h5
periods: {}
replace:
  1: /home/worker/mask-rcnn-web/testing/logos/hds.jpg
  2: /home/worker/mask-rcnn-web/testing/logos/adidas.jpg
  3: /home/worker/mask-rcnn-web/testing/logos/ps.png
  4: /home/worker/mask-rcnn-web/testing/logos/uber.jpg
  5: /home/worker/mask-rcnn-web/testing/logos/pm.jpeg
  6: /home/worker/mask-rcnn-web/testing/logos/versace.png
saving_link: result/test_1.mp4
source_link: videos/test_1.mp4
