mask_path: /home/yura/PycharmProjects/banner-detector/models/frame_mask
model_weights_path: /home/yura/PycharmProjects/banner-detector/instance/weights/mrcnn.h5
periods:
  period_1:
    finish: 275
    start: 273
replace:
  1: /home/yura/PycharmProjects/banner-detector/testing/logos/intel.png
  2: /home/yura/PycharmProjects/banner-detector/testing/logos/intel.png
  3: /home/yura/PycharmProjects/banner-detector/testing/logos/ps.png
  4: /home/yura/PycharmProjects/banner-detector/testing/logos/ps.png
  5: /home/yura/PycharmProjects/banner-detector/testing/logos/pm.jpeg
  6: /home/yura/PycharmProjects/banner-detector/testing/logos/versace.png
saving_link: testing/result/test_1.mp4
source_link: testing/videos/test_1.mp4
